name: module_external_dependencies
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_modular: ^6.3.2
  mobx_triple: ^2.0.0
  dio: ^5.2.1+1
  dartz: ^0.10.1
  permission_handler: ^10.4.3
  shared_preferences: ^2.1.2
  flutter_localization: ^0.1.14
  flutter_svg: ^2.0.6
  intl: ^0.18.1
  extended_masked_text: ^2.3.1
  nfc_manager: ^3.3.0
  pointycastle: ^3.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

